version: 2.1

orbs:
  python: circleci/python@0.2.1
  gcp-cli: circleci/gcp-cli@1.8.3 # Maybe get rid of this?

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test

  deploy:
#    working_directory: /home/circleci/5828_Team1
#    docker:
#      - image: google/cloud-sdk:alpine
#        environment:
#          GCLOUD_KEY_JSON: $(eval echo ${GCLOUD_KEY_JSON})
    executor: gcp-cli/google
    steps:
#      - gcp-cli/install
      #- gcp-cli/initialize
      - run:
          name: Authenticate with google cloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - checkout
      # - run:
      #     name: Authenticate with google cloud
      #     command: |
      #       echo $GCLOUD_KEY_JSON
      #       echo $GCLOUD_KEY_JSON > /home/circleci/.gcpkey.json
      #       gcloud auth activate-service-account --key-file=/home/circleci/.gcpkey.json
      - run:
          name: Deploy to app engine
          command: gcloud app deploy -q app.yaml

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
