version: 2.1

orbs:
  python: circleci/python@0.2.1
  node: circleci/node@2.0.1
  gcp-cli: circleci/gcp-cli@1.8.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Add config.json
          command: |
            echo $FLASK_CONFIG >> app/config.json
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test

  acceptance-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: "Install chrome driver"
          command: | 
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install google-chrome-stable
            wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv -f chromedriver /usr/local/share/chromedriver
            sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
            sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
      - run:
          name: "Run acceptance test"
          command: python "Acceptance test/acceptance.py"

  deploy:
    executor: node/default
      # name: node/default
      # tag: '12'
    # executor: gcp-cli/google
    steps:
      - checkout
      - node/install-packages:
          app-dir: "~/project/frontend"
      - run:
          name: Compile react app
          command: |
            cd frontend
            npm run build
            cd ..
      - run:
          name: Install GCP CLI
          command: | 
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk
      - run:
          name: Authenticate with google cloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - run:
          name: Add config.json
          command: |
            echo $FLASK_CONFIG >> app/config.json
      - run:
          name: Deploy to app engine
          command: |
            gcloud app deploy -q app.yaml

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - acceptance-test:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
