version: 2.1

orbs:
  python: circleci/python@0.2.1
  gcp-cli: circleci/gcp-cli@1.8.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test

  deploy:
    executor: gcp-cli/google
    steps:
      - run:
          name: Authenticate with google cloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - checkout
      - run:
          name: Deploy to app engine
          command: gcloud app deploy -q app.yaml

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
